// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ''
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'uflacs'
//  split:                          False

#ifndef __FFC_COORDINATE_MAPPING_47D54A39B1905BA707870DD870D161837535D685_H
#define __FFC_COORDINATE_MAPPING_47D54A39B1905BA707870DD870D161837535D685_H
#include "ffc_element_2da227a7dedbae4613f1fc5a8020a241f5c0e01d.h"
#include "ffc_element_8dc1bbd4542ccab4e1b97f69469d13b9615f4be1.h"
#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <ufc.h>

class ffc_coordinate_mapping_47d54a39b1905ba707870dd870d161837535d685_coordinate_mapping_main: public ufc::coordinate_mapping
{
public:

  ffc_coordinate_mapping_47d54a39b1905ba707870dd870d161837535d685_coordinate_mapping_main();

  ~ffc_coordinate_mapping_47d54a39b1905ba707870dd870d161837535d685_coordinate_mapping_main() override;

  const char * signature() const final override;

  ufc::coordinate_mapping * create() const final override;

  std::size_t geometric_dimension() const final override;

  std::size_t topological_dimension() const final override;

  ufc::shape cell_shape() const final override;

  ufc::finite_element * create_coordinate_finite_element() const final override;

  ufc::dofmap * create_coordinate_dofmap() const final override;

  void compute_physical_coordinates(
      double * x, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_reference_coordinates(
      double * X, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_reference_geometry(
      double * X, double * J, double * detJ, double * K, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_jacobians(
      double * J, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_jacobian_determinants(
      double * detJ, std::size_t num_points,
      const double * J,
      int cell_orientation) const final override;

  void compute_jacobian_inverses(
      double * K, std::size_t num_points,
      const double * J, const double * detJ) const final override;

  void compute_geometry(
      double * x, double * J, double * detJ, double * K, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_midpoint_geometry(
      double * x, double * J,
      const double * coordinate_dofs) const final override;

};

extern "C" ufc::coordinate_mapping * create_ffc_coordinate_mapping_47d54a39b1905ba707870dd870d161837535d685_coordinate_mapping_main();

#endif
