// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/usr/local/include', '/usr/local/slepc/include',
//                                   '/usr/local/slepc/linux-gnu-real-32/include', '/u
//                                  sr/local/petsc/include', '/usr/local/petsc/linux-g
//                                  nu-real-32/include', '/usr/include/x86_64-linux-gn
//                                  u/mpich', '/usr/include/hdf5/mpich', '/usr/include
//                                  /eigen3', '/usr/lib/python3/dist-packages/ffc/back
//                                  ends/ufc']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'uflacs'
//  split:                          False

#ifndef __FFC_COORDINATE_MAPPING_F2F77E7DB444E432FDEE333A42ED07962F368AA1_H
#define __FFC_COORDINATE_MAPPING_F2F77E7DB444E432FDEE333A42ED07962F368AA1_H
#include "ffc_element_1253341fc35f4f8f79308580e55af57dd57d7d4f.h"
#include "ffc_element_1da2a229dc5ec6d723c57ebafee1ef6bd212d4c2.h"
#include <algorithm>
#include <iostream>
#include <stdexcept>
#include <ufc.h>

class ffc_coordinate_mapping_f2f77e7db444e432fdee333a42ed07962f368aa1_coordinate_mapping_main: public ufc::coordinate_mapping
{
public:

  ffc_coordinate_mapping_f2f77e7db444e432fdee333a42ed07962f368aa1_coordinate_mapping_main();

  ~ffc_coordinate_mapping_f2f77e7db444e432fdee333a42ed07962f368aa1_coordinate_mapping_main() override;

  const char * signature() const final override;

  ufc::coordinate_mapping * create() const final override;

  std::size_t geometric_dimension() const final override;

  std::size_t topological_dimension() const final override;

  ufc::shape cell_shape() const final override;

  ufc::finite_element * create_coordinate_finite_element() const final override;

  ufc::dofmap * create_coordinate_dofmap() const final override;

  void compute_physical_coordinates(
      double * x, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_reference_coordinates(
      double * X, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_reference_geometry(
      double * X, double * J, double * detJ, double * K, std::size_t num_points,
      const double * x,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_jacobians(
      double * J, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs) const final override;

  void compute_jacobian_determinants(
      double * detJ, std::size_t num_points,
      const double * J,
      int cell_orientation) const final override;

  void compute_jacobian_inverses(
      double * K, std::size_t num_points,
      const double * J, const double * detJ) const final override;

  void compute_geometry(
      double * x, double * J, double * detJ, double * K, std::size_t num_points,
      const double * X,
      const double * coordinate_dofs, int cell_orientation) const final override;

  void compute_midpoint_geometry(
      double * x, double * J,
      const double * coordinate_dofs) const final override;

};

extern "C" ufc::coordinate_mapping * create_ffc_coordinate_mapping_f2f77e7db444e432fdee333a42ed07962f368aa1_coordinate_mapping_main();

#endif
